spring.application.name=ms-comprovantes
server.port=8080

# H2 - banco em memória
spring.datasource.url=jdbc:h2:mem:comprovantesdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=create-drop
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Redis
spring.data.redis.host=localhost
spring.data.redis.port=6379

# Cache TTL (segundos)
cache.redis.ttl-seconds=300

# RabbitMQ
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

# Logs
logging.level.br.com.ada=DEBUG
